Question 1.
                        Create a numpy array with filling random values, and shape of array 
should be (12,5), and pass this array from a user-defined function, and 
function should be able to return average, minimum, maximum, and 
no. of evens in your last row. 
For e.g. consider this is last row [41,52,63,96,85], 
Output:
Average -> 67.4
Minimum -> 41
Maximum -> 96
No. of evens -> 2


In [2]:
import numpy as np


In [3]:
arr1=np.random.randint(1,60,60).reshape(12,5)
arr1

array([[11, 33, 25,  4, 13],
       [24, 50,  5, 44, 54],
       [25,  9, 17, 28, 17],
       [47, 19, 49, 21, 48],
       [48,  9, 36, 49, 13],
       [16,  1, 29,  8, 14],
       [12, 39, 52, 53, 14],
       [33,  5, 57, 53, 18],
       [11, 25, 23, 25, 56],
       [15, 34,  6, 16, 24],
       [15, 50, 17, 22,  7],
       [ 2,  2, 26, 43, 44]])

In [4]:
arr1.ndim

2

In [5]:
def average(arr1):
    for i in arr1:
        avg=0
        sum=0
        for j in i:
            sum=sum +j
        avg=sum/5
        print("average->",avg)


average(arr1)

average-> 17.2
average-> 35.4
average-> 19.2
average-> 36.8
average-> 31.0
average-> 13.6
average-> 34.0
average-> 33.2
average-> 28.0
average-> 19.0
average-> 22.2
average-> 23.4


In [6]:
def maximum(arr1):
    for i in arr1:
        max=0
        for j in i:
            if j>max:
                max=j
        
        print("maximum->",max)


maximum(arr1)

maximum-> 33
maximum-> 54
maximum-> 28
maximum-> 49
maximum-> 49
maximum-> 29
maximum-> 53
maximum-> 57
maximum-> 56
maximum-> 34
maximum-> 50
maximum-> 44


In [7]:
def minimum(arr1):
    for i in arr1:
        min=10000000000
        for j in i:

            if j<min:
                min=j
        
        print("minimum->",min)


minimum(arr1)

minimum-> 4
minimum-> 5
minimum-> 9
minimum-> 19
minimum-> 9
minimum-> 1
minimum-> 12
minimum-> 5
minimum-> 11
minimum-> 6
minimum-> 7
minimum-> 2


In [8]:
def evens(arr1):
    for i in arr1:
        even=0
        for j in i:
            if j%2==0:
                even=even+1

        print("NO. of evens->",even)        


evens(arr1)

NO. of evens-> 1
NO. of evens-> 4
NO. of evens-> 1
NO. of evens-> 1
NO. of evens-> 2
NO. of evens-> 3
NO. of evens-> 3
NO. of evens-> 1
NO. of evens-> 1
NO. of evens-> 4
NO. of evens-> 2
NO. of evens-> 4


Question No.2
Let’s consider we have an array, e.g.
[[1 2 3 ],
[4 5 6 ],
[7 8 9 ]]
And apply slicing techniques to get reversed order elements of all the rows, 
like this -> [[3 2 1],
 [6 5 4],
 [9 8 7]]


In [9]:
a=np.array([[1,2,3 ],[4 ,5 ,6 ],[7 ,8, 9 ]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a.ndim

2

In [11]:
a[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])